default_platform(:android)

require 'net/http'
require 'uri'
require 'json'

platform :android do
  desc "QA 빌드 생성, Firebase 배포 및 디스코드 알림 전송"
  lane :qa do

    # 1. 릴리즈 노트 읽기 및 versionCode 자동 증가
    release_notes = File.read("release_notes.txt")
    increment_version_code(gradle_file_path: "app/build.gradle.kts")

    # 2. APK 빌드
    UI.message("📦 1. APK 빌드를 시작합니다...")
    gradle(task: "clean assembleRelease")

    # 3. Firebase App Distribution 등록
    UI.message("🔥 2. Firebase App Distribution에 업로드합니다...")
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      groups: "swyp",
      release_notes: release_notes
    )

    # 4. Discord 알림 전송
    UI.message("💬 3. 디스코드로 알림을 전송합니다...")

    webhook_url = ENV["DISCORD_WEBHOOK_URL"]
    uri = URI(webhook_url)

    # 디스코드에 보낼 메시지 포맷
    tags = ENV["DISCORD_USERS_TAG_ID"]

    payload = {
      content: "🚀 **Android QA 앱이 새로 배포되었습니다!** #{tags}",
      embeds: [
        {
          title: "📱 Firebase App Distribution",
          description: "등록된 테스터 기기의 `App Tester` 앱 또는 메일함을 확인해 주세요.",
          color: 9739627,
          fields: [
            {
              name: "📝 릴리즈 노트",
              value: release_notes
            }
          ]
        }
      ]
    }

    # HTTP 통신으로 디스코드에 쏘기
    Net::HTTP.post(uri, payload.to_json, "Content-Type" => "application/json")

    UI.success("🎉 QA 배포 및 디스코드 알림 전송이 완료되었습니다!")
  end
end
